[workspace]
resolver = "2"
members = ["cli", "codegen", "lib", "site"]

[workspace.package]
authors = ["RÃ©mi Caillot <dev@remicaillot.fr>"]
version = "1.13.28"
rust-version = "1.87.0"
edition = "2024"
