[workspace]
resolver = "2"
members = [
    "codegen",
    "lib",
    "site"
]

[workspace.package]
authors = ["RÃ©mi Caillot <dev@remicaillot.fr>"]
version = "1.14.0-beta.1"
rust-version = "1.87.0"
edition = "2024"
