tag-name = "v{{version}}"
pre-release-commit-message="Viewy.rs release v{{version}} ğŸ¾"
shared-version = true
consolidate-commits = true
allow-branch = ["main", "release/*"]
pre-release-hook = ["git", "cliff", "-r", "../", "-o", "../CHANGELOG.md", "--tag", "{{version}}" ]