[app]
name = "Viewy showcase"
favicons = [
    { rel = "shortcut icon", href="/assets/favicon.svg"}
]

[colors]
accent = { light = "#026adb", dark = "#0A84FF" }
background = { light = "#FFFFFF", dark = "#000000" }
surface = { light = "#f2f2f7", dark = "#323236" }
destructive = { light = "#d13128", dark = "#FF453A" }
success = { light = "#34C759", dark = "#30D158" }
warning = { light = "#FF9500", dark = "#FF9F0A" }

[shapes]
border-radius = 0
spacing-factor = 3

[icon-packs]
lucide = { git = "https://github.com/lucide-icons/lucide.git", path = "icons", branch = "main" }

[tokens]

font_stack = [
    { name = "roboto", url = "https://fonts.googleapis.com/css2?family=Roboto&display=swap" }

]

