[package]
name = "viewy-site"
version = "1.8.4"
authors = ["RÃ©mi Caillot <remicaillot5@gmail.com>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
viewy = { path = "../lib" }
rocket = { version = "0.5.0-rc.3", features = ["json", "secrets", "http2"]  }
chrono = { version = "0.4.19", features = ["serde"] }
